fixed NdjsonAsyncEnumerableResult ctor
creating a NdjsonAsyncEnumerableResult would always result in the following error because of wrong parameter check:
System.ArgumentNullException: Value cannot be null. (Parameter 'mediaType').